name: test

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', '3.0', 2.7, head, jruby, truffleruby-head ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache gems
    - name: Run test
      run: bundle exec rake test

    - id: build
      run: |
        bundle exec rake build
        ls -l pkg/*.gem
        shasum -a 256 pkg/*.gem
        echo "::set-output name=pkg::${GITHUB_REPOSITORY#*/}-${RUNNING_OS%-*}"
      env:
        RUNNING_OS: ${{matrix.os}}
      shell: bash
      if: ${{ matrix.ruby == '3.1' && !startsWith(matrix.os, 'ubuntu') }}
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        path: pkg/*.gem
        name: ${{steps.build.outputs.pkg}}
      if: ${{ steps.build.conclusion == 'success' }}
